YardSale/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from shop import views
from django.views.defaults import page_not_found

urlpatterns = [
    path('', views.home, name='home'),
    path("shop/", include("shop.urls")),
    path('accounts/', include('allauth.urls')),
    path('accounts/password/reset/', auth_views.PasswordResetView.as_view(), name='account_reset_password'),
    path('accounts/password/reset/done/', auth_views.PasswordResetDoneView.as_view(), name='account_reset_password_done'),
    path('accounts/password/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='account_reset_password_confirm'),
    path('accounts/password/done/', auth_views.PasswordResetCompleteView.as_view(), name='account_reset_password_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

handler404 = page_not_found

shop/urls.py
from django.urls import path, include
from . import views

app_name = "shop"
urlpatterns = [
    path("", views.home, name = "index"),
    path("<int:product_id>/detail", views.product, name = "detail"),
    path("<int:product_id>/addCart", views.add_to_cart, name = "addCart"),
    path("clothes/", views.clothing, name = "clothes"),
    path("electronics/", views.electronic, name = "electronics"),
    path('logout/', views.user_logout, name= "logout"),
    path('eliminar_item/', views.eliminar_item, name='eliminar_item'),
    path("shoppingCart", views.shopping_page, name = "shopping")
]

shop/models.py
import json

from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length = 200)
    img = models.ImageField(upload_to = 'uploads/')
    price = models.IntegerField(default = 0)
    category = models.CharField(max_length = 250, default= "category")

    def __str__(self):
          return self.name


class Carrito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Product, through='ItemCarrito')

    def __str__(self):
        return f"Carrito de {self.usuario.username}"
    
    @property
    def total(self):
        return sum(item.total for item in self.items.all())

    def get_total(self):
        return self.total

class ItemCarrito(models.Model):
    producto = models.ForeignKey(Product, on_delete=models.CASCADE)
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE, related_name='items')
    cantidad = models.PositiveIntegerField(default=1)
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.cantidad}x {self.producto.name} en {self.carrito}"
    @property
    def total(self):
        return self.cantidad * self.precio_unitario



# Saving the products into the database
def create_product(id, name, img, price, category):
        """create a product and save it into the database
        
        parameters:
            - id: AutoField/primary_key
            - name: CharField/string
            - img: ImageField/img
            - price: IntegerField/int

        returns the created product
        """
        return Product.objects.create(
        id = id, 
        name = name,
        img = img, 
        price = price, 
        category = category)

# Save the products in the database from external api

# response = requests.get("https://fakestoreapi.com/products")
# products = response.json()

# for key, value in enumerate(products):
#       create_product(value['id'], value["title"], value['image'], value['price'], value['category'])

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
    

from django.contrib.auth.models import User
# create new form

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit = True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

shop/views.py
# python build in libraries
from functools import reduce
from operator import or_
# 
from django.contrib.auth.views import logout_then_login
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from .models import Product, ItemCarrito, Carrito
from django.db.models import Q
from django.contrib.postgres.search import SearchQuery, SearchVector
# Create your views here.
from allauth.socialaccount.providers.google.views import GoogleOAuth2Adapter
from allauth.socialaccount.providers.oauth2.client import OAuth2Client
from allauth.socialaccount.providers.google.views import GoogleOAuth2Adapter
from allauth.socialaccount.providers.oauth2.views import OAuth2CallbackView

class GoogleLoginCallbackView(OAuth2CallbackView, generic.View):
    adapter_class = GoogleOAuth2Adapter
    client_class = OAuth2Client

def home(request):
    query = request.GET.get('q')
    if query:
        pattern = r'\b{}\b'.format(query)
        product_list = Product.objects.filter(
            Q(name__iregex=pattern) | Q(category__iregex=pattern)
        ).distinct()

    else:
        product_list = Product.objects.all()

    # Resto del código de la vista

    itemCarrito = ItemCarrito.objects.all()

    if request.user.is_authenticated:
        username = request.user.username
        usuario = User.objects.get(username = username)
        carrito = Carrito.objects.filter(usuario = usuario)

    total_de_productos = itemCarrito.count()

    return render(request, "shop/index.html", {
        'product_list': product_list,
        'ItemsCarrito': itemCarrito,
        'total': total_de_productos
        })

def clothing(request):
    itemCarrito = ItemCarrito.objects.all()
    total_de_productos = itemCarrito.count()
    product_clothing_list = Product.objects.filter(category__endswith = "clothing")

    return render(request, "shop/clothes.html", {
        'product_clothing_list': product_clothing_list,
        'ItemsCarrito': itemCarrito,
        'total': total_de_productos
        })
    
def electronic(request):
    itemCarrito = ItemCarrito.objects.all()
    total_de_productos = itemCarrito.count()
    product_electronics_list = Product.objects.filter(category = "electronics")

    return render(request, "shop/electronics.html", {
        'product_electronics_list': product_electronics_list,
        'ItemsCarrito': itemCarrito,
        'total': total_de_productos
        })
    
def product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    itemCarrito = ItemCarrito.objects.all()
    total = itemCarrito.count()
    return render(request, "shop/productDetail.html", {
        "product" : product,
        "ItemsCarrito": itemCarrito,
        "total": total 
    })

def register_request(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        
        # Verificar que las contraseñas coincidan
        if password1 != password2:
            messages.error(request, 'Las contraseñas no coinciden')
            return redirect('shop:register')
        
        # Iniciar sesión y redirigir al usuario a la página de inicio
        user = authenticate(request, username=username, password=password1)
        login(request, user)
        messages.success(request, '¡Registro exitoso!')
        return redirect('shop:index')
    
    return render(request, 'shop/register.html')

def user_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            # Iniciar sesión con éxito
            login(request, user)
            return redirect("shop:index")
        
        else:
            # Si el usuario no existe y no ha iniciado sesión con Facebook o Google, mostrar mensaje de error
            messages.error(request, "Credenciales incorrectas")
            return redirect("shop:login")
            
    return render(request, "shop/login.html")

def user_logout(request):
    return logout_then_login(request, login_url="https://yardsale.up.railway.app/accounts/login/")
  # Redirect to a success page.

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        username = request.POST['username']

    usuario = User.objects.get(username=username)
    if Carrito.objects.get(usuario=usuario) is not None:
        carrito = Carrito.objects.get(usuario=usuario)
    else:
        carrito = Carrito.objects.create(usuario=usuario)
        carrito = Carrito.objects.get(usuario=usuario)

    producto = Product.objects.get(name=product.name)
    item = ItemCarrito.objects.create(producto=producto, carrito=carrito, cantidad=1, precio_unitario=producto.price)
    return HttpResponseRedirect(reverse("shop:detail", args = (product.id,)))

def eliminar_item(request):
    if request.method == 'POST':
        item_id = request.POST.get('item_id')
        item = ItemCarrito.objects.get(id=item_id)
        item.delete()
    return redirect('shop:index')

def shopping_page(request):
    item_carrito = ItemCarrito.objects.all()

    if request.user.is_authenticated:
        username = request.user.username
        usuario = User.objects.get(username = username)

    carrito = Carrito.objects.get(usuario=usuario)
    total_price = carrito.get_total()
    total_de_productos = item_carrito.count()

    return render(request, "shop/shoppingPage.html", {
        'ItemsCarrito': item_carrito,
        'total': total_de_productos,
        'total_price': total_price
        })
    

    

shop/templates/shop/clothes.html
{% load static %}
{% include 'shop/header.html' %}
<body>
  <section class="main-container">
    {% include 'shop/shoppingCart.html' %}
      {% if product_clothing_list %}
          <div class="cards-container">
            {% for product in product_clothing_list  %}
            <div class="product-card">
              <form action="{% url 'shop:detail' product.id %}" method= "post">
                {% csrf_token %}
                <button>
                  <img src="{{product.img}}" alt="bike">
                </button>
                <input type="hidden" name="product" value = "product.id">
              </form>
              <div class = "product-info">
                <div >
                  <p>{{product.name}}</p>
                  <p>${{product.price}}</p>
                </div>
                <figure>
                  <button>
                    <img src="{% static 'shop/icons/bt_add_to_cart.svg' %}" alt="close">
                  </button>
                </figure>
              </div>
            </div>
            {% endfor %}
      {% else %}
              <p>No clothing are available</p>
            </div>
      {% endif %}
  </section>
    {% include 'shop/footer.html' %}
    <script src="{% static 'shop/main.js' %}"></script>
</body>
</html>

shop/templates/shop/electronics.html
{% load static %}
{% include 'shop/header.html' %}
<body>
  <section class="main-container">
    {% include 'shop/shoppingCart.html' %}
    {% if product_electronics_list %}
        <div class="cards-container">
          {% for electronic in product_electronics_list  %}
          
          <div class="product-card">
            <form action="{% url 'shop:detail' electronic.id %}" method= "post">
              {% csrf_token %}
              <button>
                <img src="{{electronic.img}}" alt="bike">
              </button>
              <input type="hidden" name="product" value = "electronic.id">
            </form>
            <div class = "product-info">
              <div >
                <p>{{electronic.name}}</p>
                <p>${{electronic.price}}</p>
              </div>
              <figure>
                <button>
                  <img src="{% static 'shop/icons/bt_add_to_cart.svg' %}" alt="close">
                </button>
              </figure>
            </div>
          </div>

            {% endfor %}
            {% else %}
            <p>No electronics are available</p>

          </div>
    {% endif %}
  </section>
    {% include 'shop/footer.html' %}
    <script src="{% static 'shop/main.js' %}"></script>
</body>
</html>

shop/templates/shop/footer.html
{% load static %}
<footer class = "footer">
    <ul class = "ul-footer">
        <li class = "footer-li"><a href="https://web.facebook.com/"><img class = "img-footer" src="{% static 'shop/icons/google.svg' %}" alt="google"></a></li>
        <li class = "footer-li"><a href="https://web.facebook.com/"><img class = "img-footer" src="{% static 'shop/icons/facebook.svg' %}" alt="facebook"></a></li>
        <li class = "footer-li"><a href="https://mail.google.com/"><img class = "img-footer" src="{% static 'shop/icons/email.svg' %}" alt="email"></a></li>
    </ul>
</footer>

shop/templates/shop/furnitures.html
{% include 'shop/header.html' %}

shop/templates/shop/header.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="icon" href="{% static 'shop/logos/favicon_yard_sale.svg' %}" type="image/svg" />
    <link
      href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;500;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'shop/reset.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    {% block css_external %}
    <link rel="stylesheet" href="{% static 'shop/style.css' %}" />
    {% endblock css_external %}
    <title>YardSale: tienda de cosas chidas</title>
  </head>

  {% block box %} {% endblock box %} {% block content %}
  <header>
    <nav>
      <img
        src="{% static 'shop/icons/icon_menu.svg' %}"
        alt="menu"
        class="menu"
      />

      <div class="navbar-left">
        <img
          src="{% static 'shop/logos/logo_yard_sale.svg' %}"
          alt="logo"
          class="logo"
        />

        <ul>
          <li>
            <a href="{% url 'shop:index' %}">All</a>
          </li>
          <li>
            <a href="{% url 'shop:clothes' %}">Clothes</a>
          </li>
          <li>
            <a href="{% url 'shop:electronics' %}">Electronics</a>
          </li>
        </ul>
      </div>

      <div class="navbar-right">
        <ul>
          <li class="navbar-email">
            {% if user.is_authenticated %}
              {{user.email}}
            {% endif %}
          </li>
          <li class="navbar-shopping-cart">
            <img
              src="{% static 'shop/icons/icon_shopping_cart.svg' %}"
              alt="shopping cart"
            />
            <div>{{total}}</div>
          </li>
        </ul>
      </div>

      <div class="desktop-menu inactive">
        <ul>
          <li>
            <a href="{% url 'shop:shopping' %}" class="title">My orders</a>
          </li>
          <li>
            <a href="{% url 'shop:logout' %}">Sign out</a>
          </li>
        </ul>
      </div>

      <div class="mobile-menu inactive">
        <ul>
          <li>
            <a href="{% url 'shop:index' %}">All</a>
          </li>
          <li>
            <a href="{% url 'shop:clothes' %}">Clothes</a>
          </li>
          <li>
            <a href="{% url 'shop:electronics' %}">Electronics</a>
          </li>
        </ul>

        <ul>
          <li>
            <a href="/">My orders</a>
          </li>
          <li>
            <a href="/">My account</a>
          </li>
        </ul>

        <ul>
          <li>
            <a href="/" class="email">platzi@example.com</a>
          </li>
          <li>
            <a href="{% url 'shop:logout' %}" class="sign-out">Sign out</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  {% endblock %}
</html>

shop/templates/shop/index.html
{% load static %}
{% include 'shop/header.html' %}
<body>
  {% include 'shop/shoppingCart.html' %}
  
  {% if user.is_authenticated %}
  {% if messages %}
  <div class="p-2">
    {% for message in messages %}
      <div class="text-center border-bottom">{{message}}</div>
    {% endfor %}
  </div>
  {% endif %}
  {% endif %}

  <section class="main-container">
    <form class = "navigator" method="GET">
      <input class = "key_word" type="text" name="q" placeholder="Buscar productos...">
      <button class = "search" type="submit"><img src="{% static 'shop/icons/magnifier.png' %}" alt=""></button>
    </form>
    {% if product_list %}
    <div class="cards-container">
      {% for product in product_list %}
      <!-- Código HTML para mostrar el producto -->
      {% endfor %}
    </div>
    {% else %}
    <p>No se encontraron productos</p>
    {% endif %}
  
    {% if product_list %}
      <div class="cards-container">

        {% for product in product_list  %}

        <div class="product-card">
          <form action="{% url 'shop:detail' product.id %}" method= "post">
            {% csrf_token %}
            <button>
              <img src="{{product.img}}" alt="bike">
            </button>
            <input type="hidden" name="product" value = "product.id">
          </form>
          <div class = "product-info">
            <div >
              <p>{{product.name}}</p>
              <p>${{product.price}}</p>
            </div>
            <form action="{% url 'shop:addCart' product.id %}" method = "POST">
              {% csrf_token %}
              <input type="hidden" name="username" value = "{{user.username}}">
              <figure>
                <button>
                  <img src="{% static 'shop/icons/bt_add_to_cart.svg' %}" alt="add">
                </button>
              </figure>
            </form>
          </div>
        </div>

          {% endfor %}
          {% else %}
          <p>No products are available</p>
        </div>
        {% endif %}
  </section>
{% include 'shop/footer.html' %}
<script src="{% static 'shop/main.js' %}"></script>
</body>
</html>

shop/templates/shop/login.html
{% comment %} {% extends 'shop/header.html' %}
{% load static %}
{% load socialaccount %}


{% block css_external %}
    <link rel="stylesheet" href="{% static 'shop/login.css' %}">
{% endblock css_external %}

{% include 'shop/messages.html' %}

{% block content %}
<body>
    {% include 'shop/messages.html' %}        
    <form class = "form" action="{% url 'shop:login' %}" method = "POST">
        {% csrf_token %}
        <div class = "fill">
            <div class = "circle"></div>
            <div class = "circle"></div>
            <div class = "circle"></div>
        </div>
        <h1>Welcome to YardSale</h1>
        <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" name= "username" id="username" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" name = "password" id="exampleInputPassword1">
        </div>
        <a href="{% provider_login_url 'google' %}">Login with Google</a>
        <button type="submit" class="btn btn-primary">Login</button>
        <div>
            <a class= "sign_up" href="{% url 'shop:register' %}">Sign up</a>
        </div>
    </form>

</body>
</html>
{% endblock content %} {% endcomment %}

shop/templates/shop/messages.html
{% if messages %} {% for message in messages %}
<div class="alert alert-dismissible {{message.tags}}">
  <button type="button" class="close" data-bs-dismiss="alert">×</button>
  <strong>{{message}}</strong>
</div>
{% endfor %} {% endif %}

shop/templates/shop/productDetail.html
{% load static %} {% include 'shop/header.html' %}
<body>
  {% include 'shop/shoppingCart.html' %}
  <div class="box">
    <div id="productDetail">
      <div class="imgContainer">
        <img src="{{product.img}}" alt="bike" />
      </div>
      <div class="product-info">
        <p>${{product.price}} US</p>
        <p>{{product.name}}</p>
        <p>
          With its practical position, this bike also fulfills a decorative
          function, add your hall or workspace.
        </p>
        <form action="{% url 'shop:addCart' product.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="username" value = "{{user.username}}">
          <button class="primary-button add-to-cart-button">
              <img
                src="{% static 'shop/icons/bt_add_to_cart.svg' %}"
                alt="add to cart"
              /> Add to cart          
          </button>
        </form>
      </div>
    </div>
  </div>
  {% include 'shop/footer.html' %}
  <script src="{% static 'shop/main.js' %}"></script>
</body>

shop/templates/shop/register.html
{% comment %} {% comment %} {% extends 'shop/header.html' %} {% load static %} {% block content %}
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
  crossorigin="anonymous"
/>
<script
  src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
  integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
  crossorigin="anonymous"
  defer
></script>
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
  integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
  crossorigin="anonymous"
  defer
></script>
{% endblock %} {% block css_external %}
<link rel="stylesheet" href="{% static 'shop/login.css' %}" />
<link rel="stylesheet" href="{% static 'shop/register.css' %}" />
{% endblock css_external %} {% comment %} Creating form for the user register
view {% endcomment %} {% block box %}
{% comment %} <form class="form" action="{% url 'shop:register' %}" method="POST">
  {% csrf_token %}
  <div class="fill">
    <div class="circle"></div>
    <div class="circle"></div>
    <div class="circle"></div>
  </div>
  <h1>Welcome to YardSale</h1>
  <div class="mb-3">
    <label for="username" class="form-label">Username</label>
    <input
      type="text"
      class="form-control"
      name="username"
      id="exampleInputEmail1"
      aria-describedby="emailHelp"
    />
    <div id="emailHelp" class="form-text">
      We'll never share your email with anyone else.
    </div>
  </div>
  <div class="mb-3">
    <label for="fname">first name</label>
    <input class="form-control" type="text" name="fname" id="" />
  </div>
  <div class="mb-3">
    <label for="lname">last name</label>
    <input class="form-control" type="text" name="lname" id="" />
  </div>
  <div class="mb-3">
    <label for="email">email</label>
    <input class="form-control" type="email" name="email" id="" />
  </div>
  <div class="mb-3">
    <label for="password1">password</label>
    <input class="form-control" type="password" name="password1" id="" />
  </div>
  <div class="mb-3">
    <label for="password2">password confirmation</label>
    <input class="form-control" type="password" name="password2" id="" />
  </div>
  <button type="submit" class="btn btn-primary">register</button>    
  <div>
    <a class="sign_up" href="{% url 'shop:login' %}"
      >Do you have an account already?. Login</a
    >
  </div>
</form>
{% endblock %} {% endcomment %} {% endcomment %} {% endcomment %}

shop/templates/shop/seleccionar_cuenta_google.html.html
{% if user.is_authenticated %}
  {% if user.social_auth %}
    <form method="POST" action="{% url 'seleccionar_cuenta_google' %}">
      {% csrf_token %}
      <select name="cuenta_google">
        {% for auth in user.social_auth %}
          {% if auth.provider == "google-oauth2" %}
            <option value="{{ auth.id }}">{{ auth.extra_data.email }}</option>
          {% endif %}
        {% endfor %}
      </select>
      <button type="submit">Seleccionar cuenta</button>
    </form>
  {% endif %}
{% endif %}

shop/templates/shop/shoppingCart.html
{% load static %}
<aside id="shoppingCart" class="inactive">
  <div class="title-container">
    <img src="{% static 'shop/icons/flechita.svg' %}" alt="arrow" />
    <p ><a class="title" href="{% url 'shop:shopping' %}">My order</a></p>
  </div>

  <div class="my-order-content">
    {% for item in ItemsCarrito  %}
    <div class="shopping-cart">
      <figure>
        <img
          src="{{item.producto.img}}"
          alt="bike"
        />
      </figure>
      <p>{{item.producto.name}}</p>
      <p>${{item.producto.price}}</p>
      <form class = "delete_product" method="post" action="{% url 'shop:eliminar_item' %}">
        {% csrf_token %}
        <input type="hidden" name="item_id" value="{{ item.id }}">
        <button class="buttonForm" type="submit">
          <img src="{% static 'shop/icons/close.png' %}" alt="close" />
        </button>
      </form>
    </div>
    {% endfor %}
      <button class="primary-button">Checkout</button>
  </div>
</aside>

shop/templates/shop/shoppingPage.html
{% load static %}
{% include 'shop/header.html' %}
<body>
{% include 'shop/shoppingCart.html' %}
<div id="shoppingCart1" >
  <div class="title-container">
    <img src="{% static 'shop/icons/flechita.svg' %}" alt="arrow" />
    <p class="title">My orders</p>
  </div>

  <div class="my-order-content">
    {% for item in ItemsCarrito  %}
    <div class="shopping-cart">
      <figure>
        <img
          src="{{item.producto.img}}"
          alt="bike"
        />
      </figure>
      <p>{{item.producto.name}}</p>
      <p>${{item.producto.price}}</p>
      <form class = "DeleteForm" method="post" action="{% url 'shop:eliminar_item' %}">
        {% csrf_token %}
        <input type="hidden" name="item_id" value="{{ item.id }}">
        <button class="buttonForm" type="submit">
          <img src="{% static 'shop/icons/close.png' %}" alt="close" />
        </button>
      </form>
    </div>
    {% endfor %}
      <div class = "total"><p>Total price</p><p>{{total_price}}</p></div>
  </div>
</div>
<script src="{% static 'shop/main.js' %}"></script>
</body>
</html>

shop/templates/shop/toys.html
{% include 'shop/header.html' %}